# Data configuration
dataset_url: "https://app.roboflow.com/ds/BZ8VwtgNPT?key=yW4cr5Fxn1"
dataset_path: "data"
image_size: 320

# Training configuration
epochs: 100
batch_size: 16
learning_rate: 0.01
model_name: "yolo11n.pt"

# Model import/export configuration
model_path: "./bsort_custom_model.pt"
infer_model_path: "./bsort-training/run/weights/best.onnx"

# Export configuration
export_formats: ["onnx", "torchscript"]
